
*-------- ------------------------------------------------------------
*-------- ---------------------------------------------------------------
S0801     Confederation Day, celebrated in Switzerland
S0801    6The start of the Garlic Festival in Gilroy, California.
S08011291 the Everlasting League forms, the basis of the Swiss Confederation.
B08011770 William Clark, explored Pacific Northwest with Lewis.
B08011779 Francis Scott Key, wrote the 'Star-Spangled Banner'.
S08011790 First U.S. Census
S08011794 Whisky Rebellion
B08011815 Richard Henry Dana, spent 2 years before the mast.
S08011852 Black Methodists in SF establish 1st black church, Zion Methodist.
S08011881 US Quarantine Station authorized for Angel Island.
S08011901 Burial within San Francisco City limits prohibited.
S08011907 Bank of Italy opens 1st branch at 3433 Mission Street.
S08011916 Hawaii National Park established.
B08011942 Karen Black Illinois
S08011946 President Truman establishes Atomic Energy Commission.
S08011953 California introduces it's Sales Tax (for Education).
S08011957 First commercial building heated by sun, Albuquerque NM
S08011958 First Class postage up to 4 cents (had been 3 cents for 26 years).
S08011961 New San Francisco Hall of Justice opens.
S08011971 CBS presents The Six Wives of Henry the VIII
B08011973 Tempestt Bledsoe
S08011981 MTV premiers
S08021873 1st trial run of an SF cable car, on Clay Street between
S08021873CKearny and Jones, downhill all the way, at 4AM.
S08021877 San Francisco Public Library opens with 5000 volumes.
B08021905 Myrna Loy, Actress                       
B08021922 Paul Laxalt, Senator                       
S08021923 President Harding dies at the Palace Hotel.
B08021924 James Baldwin, Author                        
B08021926 Betsy Bloomingdale
B08021960 Apollonia (Kotero)
S08021965 Morley Safer's sends first Vietnam report indicating we are losing
B08021986 Me!  Do programs have life?
S0803     American Family Day, 
S08031492 Columbus sets sail for 'the Indies'.
B08031811 Elisha Graves Otis, inventor of the safe elevator.
B08031901 John Stennis, Senator - Mississippi         
B08031905 Dolores Del Rio
B08031921 Mariyln Maxwell
B08031923 Anne Klein
B08031924 Leon Uris, Author -Exodus & Q B V11      
B08031926 Tony Bennett, Singer                        
S08031958 1st underwater crossing of North Pole completed, submarine Nautilus
S0804     Colorado Day, 
S08041693 Champagne is invented by Dom Perignon.
B08041755 Nicolas-Jacque Conte, invented the modern pencil.
S08041790 United States Coast Guard founded.
B08041920 Helen Thomas, Journalist                    
B08041943 Tina Cole Hollywood California
S08041958 Dumont TV Network crumbles
B08041958 Mary Decker
S08051775 the 1st Spanish ship, 'San Carlos', enters San Francisco bay.
S08051861 US levies it's first Income Tax (3% of incomes over $800).
S08051864 the spectrum of a comet observed for 1st time, by Giovanni Donati.
B08051923 Richard Kleindienst, Former Attorney General       
B08051930 Neil Armstrong, 1st Moonwalker     
B08051933 Joan Weldon
B08051953 Samantha Sang
S08051957 American Bandstand goes on network TV
S08051962 Marilyn Monroe dies at age 36
S08051963 Nuclear Test Ban Treaty signed.
B080519?? Erika Slezak Hollywood California
B080519?? Jo Collins Oregon
S0806     Independence Day, celebrated in Bolivia.
B08061809 Lord Alfred Tennyson, poet laureate of England.
S08061835 Bolivia gains it's independence
B08061881 Sir Alexander Fleming, cashed in on penicillin
B08061911 Lucille Ball, Comedian                      
B08061921 Ella Raines, Actress                       
S08061926 the first woman swims the English Channel.
B08061927 Andy Warhol, Pop Artist                    
B08061930 Abbey Lincoln
S08061945 the Atom Bomb was dropped on Hiroshima by the 'Enola Gay'.
B08061947 Sally Eaton Illinois
S08061961 Gherman S. Titov, second Russian in space aboard Vostok 2.
S08061985 Nineteenth Space Shuttle Mission - Challenger 8 returns to Earth.
B080619?? Stephane Krammer
B08071783 John Heathcoat, invented lace-making machinery
S08071807 1st servicable steamboat, the Cleremont, goes on 1st voyage.
S08071820 Potatoes first planted in Hawaii.
B08071886 Louis Alan Hazeltine, invented the neutrodyne circuit, making
B08071886Ccommercial radio possible.
B08071932 Ann Harding
B08071942 Anjanette Comer Dawson Texas
B08071942 B J Thomas, Singer                        
B08071943 Lana Cantrell Sydney Australia
B08071944 Lori Anderson, Actress                       
S08071946 First coin bearing portrait of Negro authorized
S08071959 First satellite to transmit photographs to Earth launched, Canaveral
S08071971 Apollo 15 returns to Earth.
S08071972 Joi Lansing dies at age 43
B08081763 Charles Bullfinch, 1st US professional architect
B08081908 Arthur Goldberg, Former Supreme Court Justice  
B08081910 Sylvia Sydney
B08081922 Rudi Gernreich, designed 1st women's topless swimsuit & the miniskirt
B08081923 Esther Williams, Actress                       
B08081932 Mel Tillis, Singer                        
B08081938 Connie Stevens Brooklyn N.Y.
S08091803 1st horses arrive in Hawaii.
S08091842 the US-Canada border defined by the Webster-Ashburton Treaty.
B08091913 Herman Talmadge, Senator -Georgia              
B08091930 Betty Boop
S08091945 Atom Bomb dropped on Nagasaki.
S08091956 First state-wide, state-supported educational TV network, Alabama
B08091957 Melanie Griffith
S08091974 Richard Nixon resigns presidency.
S0810     Independence Day, celebrated in Ecuador
S08101809 Ecuador gains it's independence.
B08101874 Herbert Hoover, 31st President (1929-1933)
B08101900 Norma Shearer
B08101911 Jane Wyatt, Actress                       
B08101916 Noah Beery Jr., Actor                         
B08101923 Rhonda Fleming Hollywood Cal
B08101924 Martha Hyer
B08101938 Diana Muldaur
B08101942 Betsy Johnson
B08101943 Ronnie Spector New York City
S08101948 ABC enters network TV at 7 PM - WJZ, New York
S08101973 1st BART train travels thru transbay tube to Montgomery St Station.
S08101981 Pete Rose tops Stan Musial's record of 3630 hits.
S08111888 The California Theatre closed (now a Pac Tel Phone Store).
B08111921 Alex Haley, Roots                         
B08111924 Arlene Dahl Minnesota
B08111933 Jerry Falwell, Evangelist                    
B08111937 Anna Massey
B08111941 Elizabeth Holtzman
S08111951 First color telecast of baseball game - NY city
S08111962 Andrian G. Nikolayev,third Russian in space aboard Vostok 3.
S08121851 Issac Singer granted a patent for his sewing machine.
B08121881 Cecil B. deMille, directed God.
B08121911 Mario Moreno, alias Cantinflas.
B08121912 Jane Wyatt
B08121921 Majorie Reynolds Buhl Idaho
B08121925 Dale Bumpers, Former Cabinet Member         
B08121931 William Goldman, Author                        
B08121941 Deborah Walley Bridgeport Ct
S08121953 Ann Davidson -first woman to sail solo across Atlantic arrived Miami
S08121959 First ship firing of a Polaris missile, Observation Island
S08121960 First communications satellite launched from Cape Canaveral
S08121962 Pavel R. Popovich, fourth  Russian in space aboard Vostok 4.
S08121977 First test of the Space Shuttle Enterprise.
S0813     International Left-handers Day
B08131655 Johann Christoph Denner, invented the clarinet.
B08131818 Lucy Stone, pioneer in Woman's Rights.
B08131860 Annie Oakley
S08131876 Reciprocity Treaty between US and Hawaii ratified.
B08131902 Regis Toomey, Actor                         
B08131904 Buddy Rodgers, Actor                         
B08131908 Gene Raymond, Actor                         
B08131909 John Beal, Actor                         
B08131912 Ben Hogan, Golf Pro                      
B08131921 Neville Brand, Actor                         
B08131967 Quinn Cummings
S08141846 Henry David Thoreau jailed for tax resistance.
B08141920 Nehemiah Persoff, Actor                         
B08141925 Russell Baker, Columnist                     
B08141926 Alice Ghostly Montana
S08141935 U.S. Social Security Act approved
B08141941 Connie Smith Elkhart Indiana
S08141945 VJ Day - Japan surrendered to end World War II.
B08141946 Susan St James, Actress                       
B08141946 Susan St. James Los Angeles Calif
B08141952 Debbie Meyer
B08141953 Deborah Myers Annapolis Maryland
S0815     Independence Day, celebrated in the Congo.
S0815     Liberation Day, celebrated in South Korea.
B08151769 Napoleon Bonaparte, resident of Elba
B08151803 Sir James Douglas, father of British Columbia.
S08151901 Arch Rock, danger to Bay shipping, blasted with 30 tons of
S08151901Cnitrogelatin (and that ain't jello).
B08151904 Bill Baird, Puppeteer                     
B08151912 Julia Child, The French Chef               
B08151924 Phyllis Schlafly, Right-Wing Feminist           
B08151925 Rose Marie, Actress                       
B08151931 Janice Rule Norwood Ohio
B08151933 Lori Nelson
B08151935 Abby Dalton Las Vegas
B08151943 Barbara Bouchet
S08151945 Riot in San Francisco celebrating end of World War II.
S08151945CSouth Korea liberated from Japanese rule.
B08151950 Princess Anne England
S08151960 the Congo (Brazzaville) gains it's independence.
B08161884 Hugo Gernsback, responsible for science fiction becoming an
B08161884Cindependent literary form.
B08161892 Harold Foster, cartoonist, created "Prince Valiant", known for
B08161892Cit's fine drawing and historical detail.
B08161894 George Meany, Labor Leader                  
B08161928 Ann Blyth, Actress                       
B08161930 Frank Gifford, T V Sports Announcer          
B08161931 Betsy Von Furstenberg Germany
B08161932 Eydie Gorme Bronx NY
B08161935 Julie Newmar
B08161936 Anita Gillette Baltimore Md.
B08161939 Carole Shelley London
B08161946 Leslie Ann Warren New York City
B08161958 Madonna (Ciccone) Bay City Michigan
S08161969 Woodstock festival begins in New York.
S0817     Independence Day, celebrated in Indonesia
B08171786 Davy Crockett
S08171858 1st bank in Hawaii opens.
B08171892 Mae West.  Go up and see her sometime.
S08171908 Bank of Italy opens it's new headquarters at Clay & Montgomery.
B08171914 Franklin D. Roosevelt Jr., Son Of F D R                  
B08171921 Maureen O'Hara Dublin Ireland
S08171950 Indonesia gains it's independence.
B08171958 Belinda Carlisle (The GoGos)
B08181618 Virginia Dare, 1st child born in America of English parents.
B08181834 Marshall Field, founded a Chicago-based store chain.
B08181917 Caspar Weinberger, Secretary Of Defense          
B08181922 Shelly Winters, Actress                       
B08181927 Rosalynn Carter, Mrs Jimmy Carter              
B08181933 Roman Polanski, Director                      
B08181935 Gail Fisher Orange N.J.
B08181937 Robert Redford, Actor                         
S08181958 Investigation starts of TV Game show scandal
S08181960 First photograph bounced off a satellite, Cedar Rapids, Iowa
S0819     Aviation Day
S0819    6Admission Day (celebrated in Hawaii).
B08191646 John Flamsteed, 1st astronomer royal of England.
B08191785 Seth Thomas, pioneer in mass production of clocks.
S08191826 Canada Co. chartered to colonize Upper Canada (Ontario).
B08191871 Orville Wright
B08191907 Thruston Morton, Former Senator From Kentucky  
B08191931 Willie Shoemaker, Jockey                        
B08191933 Debra Paget
B08191940 Jill St John, Actress                       
S08191942 First American offensive in Pacific in WW2, Guadalcanal, Solomon Is
S08191942 First American pilot to shoot down German fighter plane, S.F. Junkin
S08191950 ABC begins the tradition of Saturday morning kid shows
B08191956 Sue Barker
S08191960 Francis Gary Powers convicted of spying by USSR (U-2 incident)
S08191979 The crew of Soyuz 32 returns to Earth aboard Soyuz 34.
S08191982 Soyuz T-7 is launched.
S0820    6Admission Day (celebrated in Hawaii).
B08201833 Benjamin Harrison, 23rd President (1889-1893)
B08201921 Jacqueline Susann
B08201925 Lola Albright Ohio
S08201930 Dumont's first TV Broadcast
S08201930 First demonstration of home reception of television, NY city
S08201942 Dimout regulations implemented in San Francisco.
B08201946 Connie Chung, Tv Newscaster                 
S08201955 First airplane to exceed 1800 m.p.h. - H.A. Hanes, Palmdale Ca
S08201956 Republicans start convention at the Cow Palace.
S08201977 Voyager II launched.
B08211660 Hubert Gautier, engineer, wrote 1st book on bridge building.
B08211930 Princess Margaret
B08211936 Wilt Chamberlin, Basketball Player             
B08211938 Kenny Rogers, Singer                        
B08211944 Jackie DeShannon Kentucky
B08211945 Patty McCormack
S08211959 Hawaii became the 50th state.
S08211959 Hawaii becomes the 50th state
S08211965 Gemini V is launched.
S08211968 Soviet Union invades Czechoslovakia.
S08211982 Palestinian terrorists are dispersed from Beirut
S08221787 John Fitch's steamboat completes it's tests, years before
S08221787CFulton builds his steamboat.
B08221862 Claude Debussy, composer            
B08221920 Ray Bradbury, science fiction author.
B08221929 Honor Blackman London England
B08221933 Sylvia Koscina
B08221934 Diana Sands
B08221940 Valerie Harper Sufferin NY
B08221942 Kathy Lennon, Singer                        
B08221947 Cindy Williams, Actress                       
B08221949 Diana Nyad
S08231869 1st carload of freight (boots & shoes) arrives in San Francisco,
S08231869Cfrom Boston, after a 16-day rail trip.
B08231869 James "Sunny Jim" Rolph, Mayor (1912-1931), Muni backe.
S08231872 1st Japanese commercial ship visits San Francisco with a cargo of tea.
S08231889 1st ship-to-shore wireless message received in US:
S08231889CUS lightship to Cliff House.
B08231901 John Sherman Cooper, Former Senator                
B08231932 Mark Russell, Raconteur                     
B08231934 Barbara Eden Arizona
B08231942 Patricia McBride
B08231949 Shelley Long Fort Wayne Indiana
S0824  79 Pompeii is buried.
S08241814 British sack Washington, DC.
B08241816 Sir Daniel Gooch, laid 1st successful trans-Atlantic cables
S08241869 the Waffle Iron is invented.
B08241886 William Francis Gibbs, naval architect, designed the Liberty ships
S08241909 Workers start pouring concrete for the Panama Canal.
S08241932 First transcontinental non-stop flight by a woman, A.E. Putnam
S08241950 First U.S. Negro delegate to United Nations appointed - E.S. Sampson
S08241956 First non-stop transcontinental helicopter flight arrived Wash. D.C.
S08241976 Soyuz 21 returns to Earth.
S08241989 Voyager II flies past Neptune.
S0825     Independence Day, celebrated in Uruguay.
S08251825 Uruguay gains it's independence.
S08251864 Combination rail & ferry service available from SF to Alameda.
B08251910 Ruby Keeler Halifax NS
B08251918 Leonard Bernstein, Composer & Conductor          
B08251919 George Wallace, Governor Of Alabama           
B08251927 Althea Gibson, 1st black tennis champion (in a major event)
S08251929 Graf Zeppelin passes over San Francisco, headed for Los Angeles
S08251929Cafter trans-Pacific voyage from Tokyo.
S08251981 Voyager II flies past Saturn.
S08261629 Cambridge Agreement pledged.  Massachusetts Bay Co. stockholders
S08261629Cagreed to emigrate to New England.
S08261791 John Fitch granted a US patent for his working steamboat.
S08261846 W. A. Bartlett appointed 1st US mayor of Yerba Buena (SF).
B08261873 Lee De Forest, invented the Audion vacuum tube (radio tube).
B08261901 Maxwell D. Taylor, Former General                
S08261907 Houdini escapes from chains underwater at Aquatic Park in
S08261907C57 seconds.
S08261920 19th Amendment passes - Women's Suffrage granted (about time!)
B08261921 Ben Bradlee, Journalist                    
B08261935 Geraldine Ferraro, First Woman Candidate For V P 
S08261937 Pumping to build Treasure Island finished.
S08261939 First televised Major league baseball game - Reds vs Dodgers
B08261947 Candy Moore Maplewood NJ
B08261948 Valerie Simpson Bronx New York
S08261952 Fluoridation of San Francisco water begins.
S08261974 Soyuz 15 is launched.
S08261978 Soyuz 31 is launched
S08271859 1st successful oil well drilled near Titusville, Penn.
B08271882 Samuel Goldwyn, pioneer filmmaker
S08271883 Krakatoa, WEST of Java, blew apart (Top that, St Helens).
B08271899 C.S. Forester, historical novelist, created Horatio Hornblower
B08271908 Lyndon B. Johnson, 36th President (1963-1969)
B08271915 Walter Heller, Economist                     
B08271916 Martha Raye, Comedienne                    
S08271928 Kellogg-Briand Pact, where 60 nations agreed to outlaw war.
B08271929 Ira Levin, Author - Rosemary's Baby      
B08271943 Tuesday Weld, Actress                       
S08271950 General Foods blacklists Jean Muir of Aldrich Family as a communist
S08271982 Soyuz T-7 returns to Earth.
S08271985 20th Space Shuttle Mission - Discovery 6 is launched.
B08281749 Johann Wolfgang von Goethe, social philosopher
B08281921 Nancy Kulp Pennsylvania
B08281939 Cassie Mackin
B08281960 Emma Samms
S08281974 Soyuz 15 returns to Earth.
B082819?? Marla Adams
B08291899 Lyman L. Lemnitzer, Marine Corps General          
S08291914 'Arizonan' is the 1st vessel to arrive in SF via the Panama Canal.
B08291915 Ingrid Bergman Sweden
B08291917 Isabel Sanford, Actress                       
B08291923 Richard Attenborough, Actor                         
B08291938 Peter Jennings, T V Commentator               
B08291945 Wyomia Tyus (Olympic Runner)
S08291954 San Francisco International Airport (SFO) opens.
S08291965 Gemini V returns to Earth.
S08291967 The conclusion of The Fugitive
B08301797 Mary Shelley, wrote Frankenstein
S08301850 Honolulu, Hawaii becomes a city.
B08301901 Roy Wilkins, Civil Rights Leader           
B08301907 Shirley Booth, Actress                       
B08301908 Fred MacMurray, Actor                         
B08301909 Joan Blondell New York
B08301918 Ted Williams, Baseball Player               
B08301924 Regina Resnick, Opera Singer                  
B08301941 Elizabeth Ashley, Actress                       
B08301947 Peggy Lipton New York City
B08301951 Timothy Bottoms, Actor                         
S08301961 First Negro judge of a District Court confirmed - J.B. Parsons
S08301979 1st recorded occurrance of a comet hitting the sun (the energy
S08301979Creleased was about equal to 1 million hydrogen bombs).
S08301983 Eighth Space Shuttle Mission - Challenger 3 is launched.
S08301984 Twelfth Space Shuttle Mission - Discovery 1 is launched.
S08311850 The California Pioneers organized at Montgomery & Clay Streets.
S08311886 Crocker-Woolworth National Bank organized.
B08311937 Warren Berlinger, Actor                         
B08311945 Itzhak Perlman, Violinist                     
S08311955 First microwave television station operated - Lufkin, Texas
S08311955 First sun-powered automobile demonstrated, Chicago, Il.
B08311970 Jennifer Wolf, Famous Artist                 
S08311980 Solidarity Labor Union in Poland is founded.
